[package_fields]
spec_file = "eth-node-nethermind.sss"
package_name = "eth-node-nethermind"
version_number = "1.26.0"
revision_number = "1"
homepage="https://github.com/NethermindEth/nethermind"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/NethermindEth/nethermind/archive/refs/tags/1.26.0.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "4dffe64e5683cebaab0ab02c559141b844a57f4a579afeb3975608b30b7816c5"

[package_type.language_env]
language_env = "dotnet"
dotnet_version = "8.0"
dotnet_full_version = "8.0.204-1"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.2.0"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/bookworm"
