[verify]
package_hash=[
    { hash="", name= "eth-node-besu_24.3.3-1.dsc"},
    { hash="", name= "eth-node-besu_24.3.3.orig.tar.gz"},
    { hash="", name= "eth-node-besu_24.3.3-1.debian.tar.xz"},
    { hash="", name= "eth-node-besu_24.3.3-1_amd64.deb"},
]
