[verify]
package_hash=[
    # does not matter this package won't be published
   # { hash="11e6526c8511e0234241bc2a49d896de44587a3a", name= "eth-node-config-testnet_0.0.1-1.dsc"},
    #{ hash="9c41bc337d1ee49b98254f5ce2f31824a1d3da3b", name= "eth-node-config-testnet_0.0.1-1.debian.tar.xz"},
    # check for hash changes, but subpackages would already track if files are changed or not
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-config-testnet_0.0.1.orig.tar.gz"},
    # besu 
    { hash="7edba73ede2d189a78c4021bbfc16f85b97774b1", name= "eth-node-config-testnet-besu_0.0.1-1_amd64.deb"},
    # erigon 
    { hash="c4436274387ea6f4aa4f2a81a49ba1535e1a1380", name= "eth-node-config-testnet-erigon_0.0.1-1_amd64.deb"},
    # lighthouse
    { hash="02643d258a6b06f7fbb8da49293a9c8fa7afd4d0", name= "eth-node-config-testnet-lighthouse_0.0.1-1_amd64.deb"},
    # lodestar
    { hash="22692fc215610fbd30eb3b049537da1c4474ea32", name= "eth-node-config-testnet-lodestar_0.0.1-1_amd64.deb"},
    # nethermind
    { hash="2f771560eaa8dc890626a32d3ee8ca3a5597e78f", name= "eth-node-config-testnet-nethermind_0.0.1-1_amd64.deb"},
    # nimbus-eth2
    { hash="5419ed20fd38fe02a28ca50d31bcabedbccf9ca9", name= "eth-node-config-testnet-nimbus-eth2_0.0.1-1_amd64.deb"},
    # prysm
    { hash="6c94a72a1e2f0d1abb6dfa535a4900aa67a8c42d", name= "eth-node-config-testnet-prysm_0.0.1-1_amd64.deb"},
    # reth 
    { hash="a6b2b2b64849c437208e5b37e5a7c1d18539e5de", name= "eth-node-config-testnet-reth_0.0.1-1_amd64.deb"},
    # teku
    { hash="ad16bd8d7c87ce1e898fe2c7c7723d82c8bd29b6", name= "eth-node-config-testnet-teku_0.0.1-1_amd64.deb"},
    # geth
    { hash="ad16bd8d7c87ce1e898fe2c7c7723d82c8bd29b6", name= "eth-node-config-testnet-geth_0.0.1-1_amd64.deb"},
]