[verify]
package_hash=[
    # does not matter this package won't be published
   # { hash="11e6526c8511e0234241bc2a49d896de44587a3a", name= "eth-node-config-testnet_0.0.1-1.dsc"},
    #{ hash="9c41bc337d1ee49b98254f5ce2f31824a1d3da3b", name= "eth-node-config-testnet_0.0.1-1.debian.tar.xz"},
    # check for hash changes, but subpackages would already track if files are changed or not
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-config-testnet_0.0.1.orig.tar.gz"},
    # besu 
    { hash="ffd88f6493044a28aea02c53ab0ecac4633bb63b", name= "eth-node-config-testnet-besu_0.0.1-1_amd64.deb"},
    # erigon 
    { hash="392e7aea1ed0c71341c3049463a10b522e0bdea0", name= "eth-node-config-testnet-erigon_0.0.1-1_amd64.deb"},
    # lighthouse
    { hash="a9bb72a1aab7146b8f48c73dff9d0e987aeaf8d6", name= "eth-node-config-testnet-lighthouse_0.0.1-1_amd64.deb"},
    # lodestar
    { hash="971144500170f5e104bf3543b699610b0b519826", name= "eth-node-config-testnet-lodestar_0.0.1-1_amd64.deb"},
    # nethermind
    { hash="2ff332e7e7c9949f43020b516b8ba9dbf4fb022e", name= "eth-node-config-testnet-nethermind_0.0.1-1_amd64.deb"},
    # nimbus-eth2
    { hash="40e4900b3865e3ad4b7a4b2139f6762de5bdca44", name= "eth-node-config-testnet-nimbus-eth2_0.0.1-1_amd64.deb"},
    # prysm
    { hash="20bae632bc1b1cca62aef399c4c070f5d201f336", name= "eth-node-config-testnet-prysm_0.0.1-1_amd64.deb"},
    # reth 
    { hash="fe8e5e1df3246ec639d6843049291cf023173d8f", name= "eth-node-config-testnet-reth_0.0.1-1_amd64.deb"},
    # teku
    { hash="200cd0055ae3174327cb5854a19a8aafe3bb4845", name= "eth-node-config-testnet-teku_0.0.1-1_amd64.deb"},
    # geth
    { hash="290eaf55178317a505fc1720a370a736ec295efe", name= "eth-node-config-testnet-geth_0.0.1-1_amd64.deb"},
]