[package_fields]
spec_file = "eth-node-teku.sss"
package_name = "eth-node-teku"
version_number = "23.10.0"
revision_number = "1"
homepage="https://github.com/Consensys/teku"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/Consensys/teku/archive/refs/tags/23.10.0.tar.gz"
# TODO no hash provided for source code 
## Provided by debian package maintainer not by team developing the software
tarball_hash = "a937490de8afb8c8eb8f6ab486cff116bc7c6d87e97006ff69fbea0ecd2d5530"

[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_url="https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[package_type.language_env.gradle]
gradle_version="8.2"
gradle_binary_url="https://github.com/gradle/gradle-distributions/releases/download/v8.2.0/gradle-8.2-bin.zip"
gradle_binary_checksum="38f66cd6eef217b4c35855bb11ea4e9fbc53594ccccb5fb82dfd317ef8c2c5a3"


[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=false
run_piuparts=false
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""