[verify]
package_hash=[
    { hash="3c4029ca33e6f26976012c3cab2dc68f46ce30f8", name= "eth-node-testnet-service-lodestar_0.0.1-1.dsc"},
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-testnet-service-lodestar_0.0.1.orig.tar.gz"},
    { hash="bf82dcf8ae59dc94c3dbb41f5e0df8b5d15934cd", name= "eth-node-testnet-service-lodestar_0.0.1-1.debian.tar.xz"},
    { hash="49037006b70387b68d3370fa23ffb4df76b64a44", name= "eth-node-testnet-service-lodestar_0.0.1-1_all.deb"},

]