[package_fields]
spec_file = "eth-node-geth.sss"
package_name = "eth-node-geth"
version_number = "1.13.4"
revision_number = "1"
homepage="https://github.com/ethereum/go-ethereum"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/ethereum/go-ethereum/archive/refs/tags/v1.13.4.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "e74d320fe96a40686832ba0a84b6d492e30a3cbb5c156b61b52bee8edfdc6414"

[package_type.language_env]
language_env = "go"
go_version = "1.22.2"
go_binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
go_binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=true
run_piuparts=false
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""