[package_fields]
spec_file = "eth2-val-tools.sss"
package_name = "eth2-val-tools"
version_number = "0.1.1"
revision_number = "1"
homepage="https://github.com/protolambda/eth2-val-tools"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/protolambda/eth2-val-tools/archive/refs/tags/v0.1.1.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "4b940e4b3947efd9ca7126351767d55dc8c97a8e780947912a367629f0c28f85"

[package_type.language_env]
language_env = "go"
go_version = "1.22.2"
go_binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
go_binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.6"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
