[verify]
package_hash=[
    { hash="c7ba10baa3b77c7cf59cbd550809561a387abb9c", name= "eth-node-reth_<CLIENT_VERSION>-<CLIENT_REVISION>.dsc"},
    { hash="161ed6ed9273c981481c6fc637958fd5a397258c", name= "eth-node-reth_<CLIENT_VERSION>.orig.tar.gz"},
    { hash="bf845e1db24f30cca5dca1a2db9419e1d629ae63", name= "eth-node-reth_<CLIENT_VERSION>-<CLIENT_REVISION>.debian.tar.xz"},
    { hash="f52a9448604c40e774a3e26836b692a348122b80", name= "eth-node-reth_<CLIENT_VERSION>-<CLIENT_REVISION>_amd64.deb"},
]
