[verify]
package_hash=[
    # { hash="8acafcede1991021c60b6bda87134f17e22024ba", name= "eth-node-nimbus-eth2_24.6.0-1.dsc"},
    # disable as it fails day by day, we don't care about this, until the other hashes are the same
    # { hash="f0773b315ea03acaaca3d3959877e4d02758a5fd", name= "eth-node-nimbus-eth2_24.3.0.orig.tar.gz"},
    { hash="bca5018f04ae7bdb9ee09f0d540ca2b04eade6f1", name= "eth-node-nimbus-eth2_24.7.0-1.debian.tar.xz"},
    { hash="1d5e06a4a31b4f79dae8f2be99888b1f331b2678", name= "eth-node-nimbus-eth2_24.7.0-1_amd64.deb"},
]