[verify]
package_hash=[
    # { hash="5fa53247e184c57798d7cc5f6067afbfa9d3588f", name= "eth-node_1.0.0-1.dsc"},
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-sepolia_1.0.0.orig.tar.gz"},
    # TODO debian.tar.xz is not reproducible, not priority
    # { hash="036fff0b4ed98f5614af3de36ebeee9b45ade9fa", name= "eth-node-sepolia_1.0.0-1.debian.tar.xz"},
    # besu
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-besu-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-besu-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-besu-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-besu-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-besu-teku_1.0.0-1_amd64.deb"},
    # erigon
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-erigon-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-erigon-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-erigon-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-erigon-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-erigon-teku_1.0.0-1_amd64.deb"},
    # geth
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-geth-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-geth-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-geth-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-geth-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-geth-teku_1.0.0-1_amd64.deb"},
    # nethermind
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-nethermind-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-nethermind-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-nethermind-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-nethermind-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-nethermind-teku_1.0.0-1_amd64.deb"},
    # reth
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-reth-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-reth-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-reth-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-reth-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-sepolia-reth-teku_1.0.0-1_amd64.deb"},
]