[verify]
package_hash=[
    # does not matter this package won't be published
   # { hash="11e6526c8511e0234241bc2a49d896de44587a3a", name= "eth-node-config-testnet_0.0.1-1.dsc"},
    #{ hash="9c41bc337d1ee49b98254f5ce2f31824a1d3da3b", name= "eth-node-config-testnet_0.0.1-1.debian.tar.xz"},
    # check for hash changes, but subpackages would already track if files are changed or not
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-config-testnet_0.0.1.orig.tar.gz"},
    # besu 
    { hash="99582b5dc3585657c4b1b2b7056d16a0ba7cf626", name= "eth-node-config-testnet-besu_0.0.1-1_amd64.deb"},
    # erigon 
    { hash="65f61897cc83b9414ef174e37effb52a43223ab2", name= "eth-node-config-testnet-erigon_0.0.1-1_amd64.deb"},
    # lighthouse
    { hash="ace4c406726009766c58e835cc5df6db6fcf5f92", name= "eth-node-config-testnet-lighthouse_0.0.1-1_amd64.deb"},
    # lodestar
    { hash="bd2bebf42db98328c4c217f9a99fa5c3263a6997", name= "eth-node-config-testnet-lodestar_0.0.1-1_amd64.deb"},
    # nethermind
    { hash="b6d71116eee888e16b730fc5ff7f444d950b82e9", name= "eth-node-config-testnet-nethermind_0.0.1-1_amd64.deb"},
    # nimbus-eth2
    { hash="c6da26c0d24fa9e17e997a675ceae7908f82d17d", name= "eth-node-config-testnet-nimbus-eth2_0.0.1-1_amd64.deb"},
    # prysm
    { hash="0bb506b878c8945e93e3f4d6a5b74147167bb040", name= "eth-node-config-testnet-prysm_0.0.1-1_amd64.deb"},
    # reth 
    { hash="5f398da99741eb5a67a2bcf4a2cf2a9c645ac50c", name= "eth-node-config-testnet-reth_0.0.1-1_amd64.deb"},
    # teku
    { hash="c2ffd4a280f2e760d5d3acafe81a4e413e6fe85a", name= "eth-node-config-testnet-teku_0.0.1-1_amd64.deb"},
    # geth
    { hash="c704da72ca7185990e5a523bffa0b29c487cff85", name= "eth-node-config-testnet-geth_0.0.1-1_amd64.deb"},
]