[verify]
package_hash=[
    # does not matter this package won't be published
   # { hash="11e6526c8511e0234241bc2a49d896de44587a3a", name= "eth-node-config-testnet_0.0.1-1.dsc"},
    #{ hash="9c41bc337d1ee49b98254f5ce2f31824a1d3da3b", name= "eth-node-config-testnet_0.0.1-1.debian.tar.xz"},
    # check for hash changes, but subpackages would already track if files are changed or not
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-config-testnet_0.0.1.orig.tar.gz"},
    # besu 
    { hash="0953469b04f11ca31f22a78cf325b4930d500d03", name= "eth-node-config-testnet-besu_0.0.1-1_amd64.deb"},
    # erigon 
    { hash="3c11052d855cc76ced7ec5ad11823c2bc94ff6e8", name= "eth-node-config-testnet-erigon_0.0.1-1_amd64.deb"},
    # lighthouse
    { hash="bb3835115e7649358a781268605e48b144838f5a", name= "eth-node-config-testnet-lighthouse_0.0.1-1_amd64.deb"},
    # lodestar
    { hash="9afd5f8ddb2942a631fb0089bbb300266d423d8e", name= "eth-node-config-testnet-lodestar_0.0.1-1_amd64.deb"},
    # nethermind
    { hash="80e75bf7c6339d5a642e69dd9bdd71e38520376a", name= "eth-node-config-testnet-nethermind_0.0.1-1_amd64.deb"},
    # nimbus-eth2
    { hash="ea45b93edf8ba180a56ed00d550e451308280223", name= "eth-node-config-testnet-nimbus-eth2_0.0.1-1_amd64.deb"},
    # prysm
    { hash="b4855916e111eb81fa556f0d4ca0087990df7758", name= "eth-node-config-testnet-prysm_0.0.1-1_amd64.deb"},
    # reth 
    { hash="486b27b9d4acac94758462c5d1174d8734840555", name= "eth-node-config-testnet-reth_0.0.1-1_amd64.deb"},
    # teku
    { hash="dec4e5025b5c8927dc90d12d64680129bced404f", name= "eth-node-config-testnet-teku_0.0.1-1_amd64.deb"},
    # geth
    { hash="27ba31da07d368999b7d9ae056ff16f5a75a3787", name= "eth-node-config-testnet-geth_0.0.1-1_amd64.deb"},
]