[package_fields]
spec_file = "eth-node-nimbus-eth2.sss"
package_name = "eth-node-nimbus-eth2"
version_number = "23.10.0"
revision_number = "1"
homepage="https://github.com/status-im/nimbus-eth2"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/status-im/nimbus-eth2/archive/refs/tags/v23.10.0.tar.gz"
# TODO no hash provided for source code 
## Provided by debian package maintainer not by team developing the software
tarball_hash = "319ee590475c84555868d8038b0060e5a48daf01c3df39253113633b0cbe2340"

[package_type.language_env]
language_env = "nim"
nim_version = "2.0.2"
nim_binary_url = "https://nim-lang.org/download/nim-2.0.2-linux_x64.tar.xz"
nim_version_checksum = "047dde8ff40b18628ac1188baa9ca992d05f1f45c5121d1d07a76224f06e1551  nim-2.0.2-linux_x64.tar.xz"


[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=false
run_piuparts=false
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""