[verify]
package_hash=[
    # { hash="5fa53247e184c57798d7cc5f6067afbfa9d3588f", name= "eth-node_1.0.0-1.dsc"},
    { hash="b35f46d5fb424aee57b5d666e61b2eff83543aad", name= "eth-node-holesky_1.0.0.orig.tar.gz"},
    # TODO debian.tar.xz is not reproducible, not priority
    # { hash="036fff0b4ed98f5614af3de36ebeee9b45ade9fa", name= "eth-node-holesky_1.0.0-1.debian.tar.xz"},
    # besu
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-besu-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-besu-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-besu-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-besu-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-besu-teku_1.0.0-1_amd64.deb"},
    # erigon
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-erigon-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-erigon-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-erigon-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-erigon-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-erigon-teku_1.0.0-1_amd64.deb"},
    # geth
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-geth-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-geth-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-geth-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-geth-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-geth-teku_1.0.0-1_amd64.deb"},
    # nethermind
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-nethermind-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-nethermind-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-nethermind-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-nethermind-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-nethermind-teku_1.0.0-1_amd64.deb"},
    # reth
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-reth-lighthouse_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-reth-lodestar_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-reth-nimbus-eth2_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-reth-prysm_1.0.0-1_amd64.deb"},
    { hash="d7a83b680a300348d8facc9e9d13bb87b89ee83e", name= "eth-node-holesky-reth-teku_1.0.0-1_amd64.deb"},
]