[verify]
package_hash=[
    { hash="a3d9d62a7e248cbfdeb384bbc80d3b6f74ddeded", name= "eth-node-lighthouse_5.2.0-1.dsc"},
    { hash="5906d9604ab85fed6ecb44a4143fa671e7a32644", name= "eth-node-lighthouse_5.2.0.orig.tar.gz"},
    { hash="d1f7cbb5bd4f24034643f893a4031f5dc48e58a7", name= "eth-node-lighthouse_5.2.0-1.debian.tar.xz"},
    { hash="7625fec7c0d76fdc9057dfd44e9ecf1e191195b0", name= "eth-node-lighthouse_5.2.0-1_amd64.deb"},
]
