[package_fields]
spec_file = "eth-node-prysm.sss"
package_name = "eth-node-prysm"
version_number = "4.1.1"
revision_number = "1"
homepage="https://github.com/prysmaticlabs/prysm"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/prysmaticlabs/prysm/archive/refs/tags/v4.1.1.tar.gz"
# TODO no hash provided for source code 
## Provided by debian package maintainer not by team developing the software
tarball_hash = "6cd8c7d9f304e056649f0f7f71cc4e1e3cd5e7aad6d5dbb6477d5f718a322c6e"

[package_type.language_env]
language_env = "go"
go_version = "1.22.2"
go_binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
go_binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[package_type.language_env.bazelisk]
bazelisk_version="1.18.0"

[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=true
run_piuparts=true
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""
