[package_fields]
spec_file = "eth-node-nethermind.sss"
package_name = "eth-node-nethermind"
version_number = "1.21.1"
revision_number = "1"
homepage="https://github.com/NethermindEth/nethermind"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/NethermindEth/nethermind/archive/refs/tags/1.21.1.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "8c24a4ad0671fc8a2cec03d9cfb19aa3f8b82b3e572720ab224726dad05ea324"

[package_type.language_env]
language_env = "dotnet"
dotnet_version = "7.0"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.1"
debcrafter_version = "latest"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
# package directory
workdir="~/.pkg-builder/packages"
