name: Package eth-node-teku on debian 12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main     
    paths:
      - 'debian-12/eth-node-teku/**'  

jobs:
  package:
    strategy:
      matrix:
        package-name: ["eth-node-teku"]
        package-version: ["23.10.1-1"]
        codename: ["debian-12"]
    uses: ./.github/workflows/pkgbuilder-deps.yml@package
    with:
      package-name: ${{ matrix.package-name }}
      package-version: ${{ matrix.package-version }}
      codename:  ${{ matrix.codename }}

  