name: Package eth-node-geth on debian 12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main     
    paths:
      - 'debian-12/eth-node-geth/**'  

jobs:
  package:
    strategy:
      matrix:
        package-name: ["eth-node-geth"]
        package-version-with-revision: ["1.13.4-1"]
        codename: ["debian-12"]
    uses: ./.github/workflows/pkgbuilder-deps.yml
    with:
      package-name: ${{ matrix.package-name }}
      package-version-with-revision: ${{ matrix.package-version-with-revision }}
      codename:  ${{ matrix.codename }}

  