name: eth-nodes-testnet

on:
  push:
    branches:
      - feat/eth-node

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependency repository
        uses: actions/checkout@v4
        with:
          repository: eth-pkg/pkg-builder
          ref: main
          path: pkg-builder

      - name: Install pkg-builder
        run: |
          cd pkg-builder
          cargo build --release
          mkdir -p ${HOME}/.local/bin 
          mv target/release/pkg-builder ${HOME}/.local/bin
          chmod +x ${HOME}/.local/bin/pkg-builder
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          cd .. && rm -rf pkg-builder

      - name: Install debcrafter
        run: |
          wget -q https://github.com/eth-pkg/pkg-builder/releases/download/v0.1/debcrafter
          mkdir -p ${HOME}/.local/bin
          mv debcrafter ${HOME}/.local/bin
          chmod +x ${HOME}/.local/bin/debcrafter
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Create chroot env
        run: |
          cd upcoming/bookworm/amd64/eth-node-config-mainnet/1.0.0-1
          ls -al
          pkg-builder env create
          echo "${HOME}/.cache/sbuild/bookworm-amd64.tar.gz" >> $GITHUB_PATH

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build packages
        run: |
          chmod +x scripts/build.sh
          bash scripts/build.sh --network testnet
          echo "${HOME}/packages" >> $GITHUB_PATH

      - name: Add eth-nodes repository
        run: |
          sudo curl -fsSL https://packages.eth-pkg.com/keys/ethpkg-archive-keyring.asc -o /usr/share/keyrings/ethpkg-archive-keyring.asc
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ethpkg-archive-keyring.asc] http://packages.eth-pkg.com/noble-main noble main" | sudo tee -a /etc/apt/sources.list.d/ethpkg.list
          sudo apt update

      # caches packages not to hit the repository in each CI run
      - name: Cache apt packages
        uses: eth-pkg/apt-deb-cache@v0.2.4
        with:
          packages: |
            eth-node-besu \
            eth-node-erigon \
            eth-node-geth \
            eth-node-nethermind eth-node-reth \
            eth-node-lighthouse \
            eth-node-lodestar \
            eth-node-nimbus-eth2 \
            eth-node-prysm \
            eth-node-teku

      - name: Run Tests
        run: |
          sudo dpkg -i $HOME/packages/eth-node-testnet-config
          sudo dpkg -i $HOME/packages/eth-node-config-testnet-besu_0.0.1-1_all.deb
          sudo dpkg -i $HOME/packages/eth-node-config-testnet-lighthouse_0.0.1-1_all.deb
          sudo dpkg -i $HOME/packages/eth-node-testnet-service-besu_0.0.1-1_all.deb
          sudo dpkg -i $HOME/packages/eth-node-testnet-service-lighthouse_0.0.1-1_all.deb
          sudo dpkg -i $HOME/packages/eth-node-testnet
