name: eth-nodes-testnet

on:
  push:
    branches:
      - feat/eth-node

jobs:
  besu:
    name: besu
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          # - nimbus-eth2
          # - prysm
          # - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./nodes-tests
        with:
          network: testnet
          el_name: besu
          cl_name: ${{matrix.cl_name}}
