name: pkbuilder-deps

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version-with-revision:
          required: true
          type: string  
      codename:
          required: true
          type: string      

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Sbuild setup
      run: |
        sudo apt-get update
        # Note this is an older version of sbuild, no need to patch it, yet
        sudo apt install -y debhelper schroot ubuntu-dev-tools
        sudo apt-get -y install pkg-config libssl-dev uidmap
        sudo apt-get install -y libfilesys-df-perl libmime-lite-perl
        wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/sbuild_0.85.6_all.deb
        wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/libsbuild-perl_0.85.6_all.deb
        sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true


    - name: pkg-builder
      run: |
        wget https://github.com/eth-pkg/pkg-builder/releases/download/v0.1/pkg-builder
        wget https://github.com/eth-pkg/pkg-builder/releases/download/v0.1/debcrafter
        mkdir -p ${HOME}/.local/bin 
        mv pkg-builder ${HOME}/.local/bin
        mv debcrafter ${HOME}/.local/bin 
        chmod +x ${HOME}/.local/bin/pkg-builder
        chmod +x ${HOME}/.local/bin/debcrafter
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Checkout repository
      uses: actions/checkout@v4    
    
    - name: Create env
      run: pkg-builder build-env create ${{ inputs.codename }}/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml


    - name: Create package
      run: pkg-builder package ${{ inputs.codename }}/${{inputs.package-name}}/${{ inputs.package-version-with-revision }}/pkg-builder.toml