name: regtest

on:
  push:
    branches:
      - feat/eth-node

jobs:
  besu:
    name: testnet besu
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          - nimbus-eth2
          # - prysm
          - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: testnet
          el_name: besu
          cl_name: ${{matrix.cl_name}}
  erigon:
    name: testnet erigon
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          - nimbus-eth2
          # - prysm
          - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: testnet
          el_name: erigon
          cl_name: ${{matrix.cl_name}}

  geth:
    name: testnet geth
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          - nimbus-eth2
          # - prysm
          - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: testnet
          el_name: geth
          cl_name: ${{matrix.cl_name}}

  nethermind:
    name: testnet nethermind
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          - nimbus-eth2
          # - prysm
          - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: testnet
          el_name: nethermind
          cl_name: ${{matrix.cl_name}}

  reth:
    name: testnet reth
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cl_name:
          - lighthouse
          # - lodestar
          - nimbus-eth2
          # - prysm
          - teku
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: testnet
          el_name: reth
          cl_name: ${{matrix.cl_name}}
