name: regtest

on:
  push:
    branches:
      - feat/eth-node

jobs:
  test:
    name: regtest
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - el_name: besu
            cl_name: lighthouse
            validator_name: lighthouse
          - el_name: besu
            cl_name: lighthouse
            validator_name: lodestar
          - el_name: besu
            cl_name: lighthouse
            validator_name: nimbus-eth2
          - el_name: besu
            cl_name: lighthouse
            validator_name: prysm
          - el_name: besu
            cl_name: lighthouse
            validator_name: teku

          - el_name: besu
            cl_name: lodestar
            validator_name: lighthouse
          - el_name: besu
            cl_name: lodestar
            validator_name: lodestar
          - el_name: besu
            cl_name: lodestar
            validator_name: nimbus-eth2
          - el_name: besu
            cl_name: lodestar
            validator_name: prysm
          - el_name: besu
            cl_name: lodestar
            validator_name: teku

          - el_name: besu
            cl_name: nimbus-eth2
            validator_name: lighthouse
          - el_name: besu
            cl_name: nimbus-eth2
            validator_name: lodestar
          - el_name: besu
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2
          - el_name: besu
            cl_name: nimbus-eth2
            validator_name: prysm
          - el_name: besu
            cl_name: nimbus-eth2
            validator_name: teku

          - el_name: besu
            cl_name: prysm
            validator_name: lighthouse
          - el_name: besu
            cl_name: prysm
            validator_name: lodestar
          - el_name: besu
            cl_name: prysm
            validator_name: nimbus-eth2
          - el_name: besu
            cl_name: prysm
            validator_name: prysm
          - el_name: besu
            cl_name: prysm
            validator_name: teku

          - el_name: besu
            cl_name: teku
            validator_name: lighthouse
          - el_name: besu
            cl_name: teku
            validator_name: lodestar
          - el_name: besu
            cl_name: teku
            validator_name: nimbus-eth2
          - el_name: besu
            cl_name: teku
            validator_name: prysm
          - el_name: besu
            cl_name: teku
            validator_name: teku

          - el_name: erigon
            cl_name: lighthouse
            validator_name: lighthouse
          - el_name: erigon
            cl_name: lighthouse
            validator_name: lodestar
          - el_name: erigon
            cl_name: lighthouse
            validator_name: nimbus-eth2
          - el_name: erigon
            cl_name: lighthouse
            validator_name: prysm
          - el_name: erigon
            cl_name: lighthouse
            validator_name: teku

          - el_name: erigon
            cl_name: lodestar
            validator_name: lighthouse
          - el_name: erigon
            cl_name: lodestar
            validator_name: lodestar
          - el_name: erigon
            cl_name: lodestar
            validator_name: nimbus-eth2
          - el_name: erigon
            cl_name: lodestar
            validator_name: prysm
          - el_name: erigon
            cl_name: lodestar
            validator_name: teku

          - el_name: erigon
            cl_name: nimbus-eth2
            validator_name: lighthouse
          - el_name: erigon
            cl_name: nimbus-eth2
            validator_name: lodestar
          - el_name: erigon
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2
          - el_name: erigon
            cl_name: nimbus-eth2
            validator_name: prysm
          - el_name: erigon
            cl_name: nimbus-eth2
            validator_name: teku

          - el_name: erigon
            cl_name: prysm
            validator_name: lighthouse
          - el_name: erigon
            cl_name: prysm
            validator_name: lodestar
          - el_name: erigon
            cl_name: prysm
            validator_name: nimbus-eth2
          - el_name: erigon
            cl_name: prysm
            validator_name: prysm
          - el_name: erigon
            cl_name: prysm
            validator_name: teku

          - el_name: erigon
            cl_name: teku
            validator_name: lighthouse
          - el_name: erigon
            cl_name: teku
            validator_name: lodestar
          - el_name: erigon
            cl_name: teku
            validator_name: nimbus-eth2
          - el_name: erigon
            cl_name: teku
            validator_name: prysm
          - el_name: erigon
            cl_name: teku
            validator_name: teku

          - el_name: geth
            cl_name: lighthouse
            validator_name: lighthouse
          - el_name: geth
            cl_name: lighthouse
            validator_name: lodestar
          - el_name: geth
            cl_name: lighthouse
            validator_name: nimbus-eth2
          - el_name: geth
            cl_name: lighthouse
            validator_name: prysm
          - el_name: geth
            cl_name: lighthouse
            validator_name: teku

          - el_name: geth
            cl_name: lodestar
            validator_name: lighthouse
          - el_name: geth
            cl_name: lodestar
            validator_name: lodestar
          - el_name: geth
            cl_name: lodestar
            validator_name: nimbus-eth2
          - el_name: geth
            cl_name: lodestar
            validator_name: prysm
          - el_name: geth
            cl_name: lodestar
            validator_name: teku

          - el_name: geth
            cl_name: nimbus-eth2
            validator_name: lighthouse
          - el_name: geth
            cl_name: nimbus-eth2
            validator_name: lodestar
          - el_name: geth
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2
          - el_name: geth
            cl_name: nimbus-eth2
            validator_name: prysm
          - el_name: geth
            cl_name: nimbus-eth2
            validator_name: teku

          - el_name: geth
            cl_name: prysm
            validator_name: lighthouse
          - el_name: geth
            cl_name: prysm
            validator_name: lodestar
          - el_name: geth
            cl_name: prysm
            validator_name: nimbus-eth2
          - el_name: geth
            cl_name: prysm
            validator_name: prysm
          - el_name: geth
            cl_name: prysm
            validator_name: teku

          - el_name: geth
            cl_name: teku
            validator_name: lighthouse
          - el_name: geth
            cl_name: teku
            validator_name: lodestar
          - el_name: geth
            cl_name: teku
            validator_name: nimbus-eth2
          - el_name: geth
            cl_name: teku
            validator_name: prysm
          - el_name: geth
            cl_name: teku
            validator_name: teku

          - el_name: nethermind
            cl_name: lighthouse
            validator_name: lighthouse
          - el_name: nethermind
            cl_name: lighthouse
            validator_name: lodestar
          - el_name: nethermind
            cl_name: lighthouse
            validator_name: nimbus-eth2
          - el_name: nethermind
            cl_name: lighthouse
            validator_name: prysm
          - el_name: nethermind
            cl_name: lighthouse
            validator_name: teku

          - el_name: nethermind
            cl_name: lodestar
            validator_name: lighthouse
          - el_name: nethermind
            cl_name: lodestar
            validator_name: lodestar
          - el_name: nethermind
            cl_name: lodestar
            validator_name: nimbus-eth2
          - el_name: nethermind
            cl_name: lodestar
            validator_name: prysm

          - el_name: nethermind
            cl_name: lodestar
            validator_name: teku

          - el_name: nethermind
            cl_name: nimbus-eth2
            validator_name: lighthouse
          - el_name: nethermind
            cl_name: nimbus-eth2
            validator_name: lodestar
          - el_name: nethermind
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2
          - el_name: nethermind
            cl_name: nimbus-eth2
            validator_name: prysm
          - el_name: nethermind
            cl_name: nimbus-eth2
            validator_name: teku

          - el_name: nethermind
            cl_name: prysm
            validator_name: lighthouse
          - el_name: nethermind
            cl_name: prysm
            validator_name: lodestar
          - el_name: nethermind
            cl_name: prysm
            validator_name: nimbus-eth2
          - el_name: nethermind
            cl_name: prysm
            validator_name: prysm
          - el_name: nethermind
            cl_name: prysm
            validator_name: teku

          - el_name: nethermind
            cl_name: teku
            validator_name: lighthouse
          - el_name: nethermind
            cl_name: teku
            validator_name: lodestar
          - el_name: nethermind
            cl_name: teku
            validator_name: nimbus-eth2
          - el_name: nethermind
            cl_name: teku
            validator_name: prysm
          - el_name: nethermind
            cl_name: teku
            validator_name: teku

          - el_name: reth
            cl_name: lighthouse
            validator_name: lighthouse
          - el_name: reth
            cl_name: lighthouse
            validator_name: lodestar
          - el_name: reth
            cl_name: lighthouse
            validator_name: nimbus-eth2
          - el_name: reth
            cl_name: lighthouse
            validator_name: prysm
          - el_name: reth
            cl_name: lighthouse
            validator_name: teku

          - el_name: reth
            cl_name: lodestar
            validator_name: lighthouse
          - el_name: reth
            cl_name: lodestar
            validator_name: lodestar
          - el_name: reth
            cl_name: lodestar
            validator_name: nimbus-eth2
          - el_name: reth
            cl_name: lodestar
            validator_name: prysm
          - el_name: reth
            cl_name: lodestar
            validator_name: teku

          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: lighthouse
          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: lodestar
          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2
          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: prysm
          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: teku

          - el_name: reth
            cl_name: prysm
            validator_name: lighthouse
          - el_name: reth
            cl_name: prysm
            validator_name: lodestar
          - el_name: reth
            cl_name: prysm
            validator_name: nimbus-eth2
          - el_name: reth
            cl_name: prysm
            validator_name: prysm
          - el_name: reth
            cl_name: prysm
            validator_name: teku

          - el_name: reth
            cl_name: teku
            validator_name: lighthouse
          - el_name: reth
            cl_name: teku
            validator_name: lodestar
          - el_name: reth
            cl_name: teku
            validator_name: nimbus-eth2
          - el_name: reth
            cl_name: teku
            validator_name: prysm
          - el_name: reth
            cl_name: teku
            validator_name: teku


      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: tests
        if: matrix.el_name == 'reth' && matrix.cl_name == matrix.validator_name
        uses: ./network-tests
        with:
          network: regtest
          el_name: reth
          cl_name: ${{matrix.cl_name}}
          validator_name: ${{matrix.cl_name}}
