name: regtest

on:
  push:
    branches:
      - feat/eth-node

jobs:
  # besu:
  #   name: regtest besu
  #   runs-on: ubuntu-24.04
  #   strategy:
  #     matrix:
  #       cl_name:
  #         - lighthouse
  #         - lodestar
  #         - nimbus-eth2
  #         - prysm
  #         - teku
  #     fail-fast: false
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - uses: ./network-tests
  #       with:
  #         network: regtest
  #         el_name: besu
  #         cl_name: ${{matrix.cl_name}}
  # erigon:
  #   name: regtest erigon
  #   runs-on: ubuntu-24.04
  #   strategy:
  #     matrix:
  #       cl_name:
  #         - lighthouse
  #         - lodestar
  #         - nimbus-eth2
  #         - prysm
  #         - teku
  #     fail-fast: false
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - uses: ./network-tests
  #       with:
  #         network: regtest
  #         el_name: erigon
  #         cl_name: ${{matrix.cl_name}}

  # geth:
  #   name: regtest geth
  #   runs-on: ubuntu-24.04
  #   strategy:
  #     matrix:
  #       cl_name:
  #         - lighthouse
  #         - lodestar
  #         - nimbus-eth2
  #         - prysm
  #         - teku
  #     fail-fast: false
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - uses: ./network-tests
  #       with:
  #         network: regtest
  #         el_name: geth
  #         cl_name: ${{matrix.cl_name}}

  # nethermind:
  #   name: regtest nethermind
  #   runs-on: ubuntu-24.04
  #   strategy:
  #     matrix:
  #       cl_name:
  #         - lighthouse
  #         - lodestar
  #         - nimbus-eth2
  #         - prysm
  #         - teku
  #     fail-fast: false
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - uses: ./network-tests
  #       with:
  #         network: regtest
  #         el_name: nethermind
  #         cl_name: ${{matrix.cl_name}}

  test:
    name: regtest
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include: 
          - el_name: reth 
            cl_name: lighthouse
            validator_name: lighthouse
            
          - el_name: reth
            cl_name: lodestar
            validator_name: lodestar

          - el_name: reth
            cl_name: nimbus-eth2
            validator_name: nimbus-eth2

          - el_name: reth
            cl_name: prysm
            validator_name: prysm

          - el_name: reth 
            cl_name: teku
            validator_name: teku

      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./network-tests
        with:
          network: regtest
          el_name: reth
          cl_name: ${{matrix.cl_name}}
          validator_name: ${{matrix.cl_name}}
